extends: default
rules:
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
  line-length: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: whatever
  colons: enable
  commas: enable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
  empty-values: disable
  hyphens: enable
  key-duplicates: enable
  key-ordering: disable
  new-line-at-end-of-file: disable
  new-lines: disable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: disable
  truthy: disable
