---
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-ca
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik"
data:
  root_ca.crt: |
    {{- .Values.rootCA | nindent 4 }}
