{{- if .Values.providerConfig.aws.enabled }}
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.providerConfig.aws.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  credentials:
    source: {{ .Values.providerConfig.aws.credentials.source }}
    secretRef:
      name: {{ .Values.providerConfig.aws.credentials.secretRef.name }}
      namespace: {{ .Values.providerConfig.aws.credentials.secretRef.namespace }}
      key: {{ .Values.providerConfig.aws.credentials.secretRef.key }}
{{- end }}
