{{- if .Values.infisical.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}-infisical-backend
spec:
  provider:
    infisical:
      hostAPI: {{ .Values.infisical.hostAPI | quote }}
      auth:
        universalAuthCredentials:
          clientId:
            name: {{ printf "%s-%s" .Release.Name .Values.infisical.auth.universalAuth.credentialsSecretRef.name | quote }}
            key: {{ .Values.infisical.auth.universalAuth.credentialsSecretRef.clientId | quote }}
            namespace: {{ .Release.Namespace }}
          clientSecret:
            name: {{ printf "%s-%s" .Release.Name .Values.infisical.auth.universalAuth.credentialsSecretRef.name | quote }}
            key: {{ .Values.infisical.auth.universalAuth.credentialsSecretRef.clientSecret | quote }}
            namespace: {{ .Release.Namespace }}
      secretsScope:
        projectSlug: {{ .Values.infisical.secretsScope.projectSlug | quote }}
        environmentSlug: {{ .Values.infisical.secretsScope.environmentSlug | quote }}
        secretsPath: {{ .Values.infisical.secretsScope.secretsPath | quote }}
        recursive: {{ .Values.infisical.secretsScope.recursive }}
{{- end }}
