{{- if .Values.infisical.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}-infisical-backend
spec:
  provider:
    infisical:
      host:
        apiUrl: {{ .Values.infisical.hostAPI | quote }}
      auth:
        universalAuthCredentials:
          clientId:
            name: {{ printf "%s-%s" .Release.Name .Values.infisical.auth.universalAuth.credentialsSecretRef.name | quote }}
            key: {{ .Values.infisical.auth.universalAuth.credentialsSecretRef.clientId | quote }}
            namespace: {{ .Release.Namespace }}
          clientSecret:
            name: {{ printf "%s-%s" .Release.Name .Values.infisical.auth.universalAuth.credentialsSecretRef.name | quote }}
            key: {{ .Values.infisical.auth.universalAuth.credentialsSecretRef.clientSecret | quote }}
            namespace: {{ .Release.Namespace }}
{{- end }}
