{{- if .Values.vault.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.vault.auth.tokenSecretRef.name }}
type: Opaque
stringData:
  {{ .Values.vault.auth.tokenSecretRef.key }}: ""
{{- end }}
{{- if .Values.infisical.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.infisical.auth.universalAuth.credentialsSecretRef.name }}
type: Opaque
stringData:
  {{ .Values.infisical.auth.universalAuth.credentialsSecretRef.clientId }}: ""
  {{ .Values.infisical.auth.universalAuth.credentialsSecretRef.clientSecret }}: ""
{{- end }}
