{{- if .Values.vault.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}-vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ printf "%s-%s" .Release.Name .Values.vault.auth.tokenSecretRef.name | quote }}
          key: {{ .Values.vault.auth.tokenSecretRef.key | quote }}
          namespace: {{ .Release.Namespace }}
{{- end }}
