---
infisical:
  domain: lab.internal

infisical-standalone:
  infisical:
    image:
      repository: infisical/infisical
      tag: "v0.151.0"
      pullPolicy: IfNotPresent
    replicaCount: 1
  ingress:
    enabled: false
    nginx:
      enabled: false
  postgresql:
    enabled: true
  redis:
    enabled: true
