---
infisical:
  domain: lab.internal

infisical-standalone:
  infisical:
    fullnameOverride: infisical
    replicaCount: 1
  ingress:
    enabled: false
    nginx:
      enabled: false
  postgresql:
    enabled: true
  redis:
    enabled: true
