grafana:
  host: grafana.lab.internal

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  grafana:
    enabled: true
    adminPassword: admin
    defaultDatasourceEnabled: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s/grafana"
        serve_from_sub_path: true
  alertmanager:
    enabled: true
