---
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  grafana:
    enabled: true
    adminPassword: admin
    defaultDatasourceEnabled: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
    grafana.ini:
      server:
        domain: lab.internal
        root_url: "%(protocol)s://grafana.%(domain)s"
        serve_from_sub_path: true
  alertmanager:
    enabled: true

kubePrometheusStackReadinessHook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
