---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: external-secrets-vault-token
      jsonPointers:
        - /data
        - /stringData
    - group: ""
      kind: Secret
      name: external-secrets-infisical-credentials
      jsonPointers:
        - /data
        - /stringData
  project: platform-apps
  source:
    repoURL: https://github.com/ssbagwe/gitops-lab
    targetRevision: main
    path: argocd-apps/helm-charts/platform-apps/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
