---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-ca
  namespace: argocd
spec:
  project: platform-apps
  source:
    repoURL: https://smallstep.github.io/helm-charts/
    targetRevision: 1.29.0
    chart: step-certificates
    helm:
      values: |
        # Add ACME provisioner after bootstrap init
        ca:
          bootstrap:
            postInitHook: |
              step ca provisioner add acme --type ACME
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
